#!/usr/bin/env bash
# Christopher Grossack's functions
#
# NOTE: I export two more functions in prompt
# `ps1_on` and `ps1_off`
#
# I put them there because they really belong
# with the prompt, not with these functions.
#
# See the rest of my dotfiles here:
# https://github.com/HallaSurvivor/dotfiles

# Makes moving upwards nicer
function ..     { cd ..; }
function ...    { cd ../..; }
function ....   { cd ../../..; }
function .....  { cd ../../../..; }
function ...... { cd ../../../../..; }

function cdd { cd ~/dotfiles; }

# reload bashrc
function reload { cd; source ~/.bashrc; cd -; }

# for some reason there's no way to set your default regextype in find...
function findr { dir=$1; shift; find $dir -regextype posix-egrep $*; }

# Yes. I'm too lazy to type those extra two letters
alias g=git

# So I'm DEFINITELY too lazy to not have git still autocomplete stuff
__git_complete g _git

# Again. I'm actually this lazy
alias v=nvim
